Scrape 2016 term
everypolitician-scrapers/samoa-parliament pull request #1
Opened 2016-10-26 16:02 UTC by ondenman

New term data is available on the webpage.

The data types and layout differs from the previous term. 

The member list is presented in a single table. It gives data for name, district and party.

Source: http://www.palemene.ws/new/members-of-parliament/members-of-the-xvi-parliament/

2016-10-26 18:47 UTC, tmtmtmtm requested changes
You should include the relevant section of the checklist here, as it would reveal several key steps that haven't been done…

2016-10-26 18:47 UTC, tmtmtmtm commented on scraper.rb
> +end
What is this function for?

2016-10-26 18:47 UTC, tmtmtmtm commented on scraper.rb
> +      party: name_and_party.match(/\(([A-Z]+)/)[1].tidy,
This is the `party_id`. You also need to add the `party` as well.

2016-10-26 18:47 UTC, tmtmtmtm commented on scraper.rb
>    unless (next_page = noko.css('div.ngg-navigation a.next/@href')).empty?
Is this section still required?

2016-11-14 12:42 UTC, tmtmtmtm requested changes
The logic for handling all the titles here is so complex that I think this could usefully have a few test-cases.

I also think it's worth switching this to the new `scraped-page` approach now, rather than operating slightly differently from how that works.

2016-11-14 12:42 UTC, tmtmtmtm commented on scraper.rb
> +# not capitalized in the same way as the trible names of other members. We're doing this now
typo here, and on line above: trible → tribal

2016-11-14 12:42 UTC, tmtmtmtm commented on lib/members.rb
> +  end
It's not obvious why you have a field here that is simply calling another public method.

2016-12-02 11:50 UTC, ondenman commented
Closing in favour of: https://github.com/everypolitician-scrapers/samoa-parliament/pull/1

2016-12-02 11:50 UTC, closed without merging